select var_a where brack_open dbr_Taconic_Mountains <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bellatrix <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biskupice,_Środa_Wielkopolska_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Agnicourt-et-Séchelles <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dodds_Township,_Jefferson_County,_Illinois <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Col_du_Galibier <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Kishan,_Iran <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Italian_East_Africa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Sacred_Heart_Cathedral,_Maliana <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Caer_Llugwy <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cienfuegos_Province <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Whidbey_Island <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Muri,_Razavi_Khorasan <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_First_Presbyterian_Church_(Napa,_California) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_363_Padua <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Triton_(moon) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_County_of_Stolberg <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cordillera_Occidental_(Colombia) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Drage,_Nordfriesland <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_First_Presbyterian_Church_(Poughkeepsie,_New_York) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Balu,_West_Azerbaijan <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bevern_(Samtgemeinde) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Aperture <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Broad_Water <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Supermarket <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Côte-d'Or <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Carbonate,_Lombardy <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Hall_Island_(Arctic) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_2_Pallas <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akbarabad,_Mobarakeh <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_205_Martha <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Betelgeuse <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Isère <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biskupice_(Svitavy_District) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Aappilattoq,_Kujalleq <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bucktown,_Pennsylvania <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Silk_Road <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Crans,_Jura <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Charmoille,_Haute-Saône <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Turbopump <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Lyell_Island <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Němčice_(Kroměříž_District) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Latin_square <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Swan_Lake_(Alaska) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Atoll <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Supermarket <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-de-Flée <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bry,_Nord <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Organisation_of_African_Unity <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_United_Nations_Interim_Administration_Mission_in_Kosovo <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Werder,_Ethiopia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boulogne,_Vendée <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Němčice_(Kroměříž_District) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Balloo,_County_Antrim <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Sankt_Martin_an_der_Raab <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boianu_Mare <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ashgrove,_Moray <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Sidewalk <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Crépy,_Aisne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bonneuil-Matours <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Chagai,_Pakistan <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Polder <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akari_(satellite) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Berndorf,_Lower_Austria <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Casaleggio_Novara <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_205_Martha <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Merville,_Haute-Garonne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Church_of_the_Ascension,_Roman_Catholic_(Manhattan) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ursa_Major <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Tax_law <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Aappilattoq,_Kujalleq <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Almohad_Caliphate <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_New_Netherland <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-des-Landes <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dali_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Colter's_Hell <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Al_Khawr,_Yemen <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Cyprien,_Loire <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Stadio_Comunale_(Chiasso) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bow_Bridge,_Western_Australia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_United_Nations_Interim_Administration_Mission_in_Kosovo <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_El_Rosal,_Cundinamarca <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Beauregard-de-Terrasson <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Interior_(topology) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_3737_Beckman <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cedar_Township,_Floyd_County,_Iowa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bourguignon-lès-Conflans <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dolní_Hořice <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Netherlands_New_Guinea <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_First_Presbyterian_Church_(Racine,_Wisconsin) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Castile_(historical_region) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cienfuegos_Province <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dommartin,_Ain <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_253_Mathilde <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cape_Felt <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biskupice_Oławskie <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cucumber_sandwich <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Wedge_Ridge <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Curran_Township,_Sangamon_County,_Illinois <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-sur-Charente <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-sur-Héry <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_3753_Cruithne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_The_Tower_at_Dubai_Creek_Harbour <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_1374_Isora <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ruś,_Olsztyn_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Vela_(constellation) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boissy-aux-Cailles <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Italian_East_Africa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Shang_dynasty <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Red_Bull_Arena_(Leipzig) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Changi_Business_Park <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Agia,_Larissa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_County_of_Stolberg <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_70_Virginis <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boissy-le-Bois <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bely_Island <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Al-Rastan <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-du-Chemin <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Financial_market <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cape_Breton_South_(federal_electoral_district) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Schengen_Area <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dommartin-le-Coq <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Schloßberg_(Leibnitz) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Court_of_Wards_and_Liveries <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Fara_Olivana_con_Sola <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Białobrzegi,_Płock_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-la-Vallée <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akbarabad-e_Hejri <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cool_(district_of_Rotterdam) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Al-Berka <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Yosemite_Valley <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_4659_Roddenberry <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Carpenter,_Wyoming <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Conflans-sur-Lanterne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_White_dwarf <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ega_(river) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Arab_League <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Duns_Tew <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Hautes-Alpes <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Encyclopedia_Astronautica <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Adra,_Estonia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Organisation_of_African_Unity <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Finistère <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Rio_Minho_(Jamaica) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Albireo <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Olmedo_Canton,_Loja <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dommartin-lès-Cuiseaux <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cove,_Hampshire <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Umayyad_Caliphate <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Janów,_Chełm_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Barzun,_Pyrénées-Atlantiques <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Brody_(air_base) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Březnice_(Tábor_District) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Raging_River <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bonneuil,_Indre <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Crown_of_Aragon <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Mariner_8 <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akrotiri_Peninsula_(Cyprus) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Breitscheid,_Mainz-Bingen <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_CYGM_filter <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Sankt_Martin,_Germany <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dublin_Pearse_railway_station <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Melkite_Greek_Catholic_Eparchy_of_Saint-Sauveur_of_Montréal <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Monsey,_Benin <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Charlotte_Harbor_and_Northern_Railway_Depot <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-Lalande <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Brody,_Zielona_Góra_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Cyprien,_Pyrénées-Orientales <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Stadio_Comunale_Bellinzona <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-du-Chemin <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Glarus_Alps <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Plaisance,_Dordogne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Pioneer_10 <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Centerton,_Burlington_County,_New_Jersey <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Duchy_of_Mecklenburg-Strelitz <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Efrat <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bakewell_Island <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Jin_dynasty_(265–420) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Vermont <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Plaisance-du-Sud <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur_(electoral_district) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Crépy,_Pas-de-Calais <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biotope <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Taq_Kasra <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ahigal_de_Villarino <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Enskede-Årsta-Vantör <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bilaspur,_Gautam_Buddh_Nagar <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boma_ya_Ulanga <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-Lendelin <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-de-Landemont <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Episcopal_Church_of_the_Nativity_(Union,_South_Carolina) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Condorcet,_Drôme <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Eisberg_(Moosbach) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-de-Ginestoux <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Anglo-Australian_Planet_Search <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Carville-Pot-de-Fer <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Castelvecchio_di_Rocca_Barbena <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dalmatia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Billups_House <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Condorcet,_Drôme <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-d'Émalleville <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bever_(Weser) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akbarabad,_Esmaili <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ursa_Minor <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cervino,_Campania <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Corfu <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Belleau,_Aisne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Peckforton_Castle <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Hubble_Space_Telescope <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_2009_Voloshina <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bockhorn,_Bavaria <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bazar,_Łódź_Voivodeship <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_280_Philia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Turbomolecular_pump <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Kültepe <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biotope <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bilaspur,_Gautam_Buddh_Nagar <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Lancang_Lahu_Autonomous_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Mariner_10 <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Wyoming <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boca_de_Potrerillos <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Němčice_(Blansko_District) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Adirondack_Mountains <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_9423_Abt <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dog_Lake_(Brighton,_Utah) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Coin-sur-Seille <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Adirondack_Mountains <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cedar_Township,_Cherokee_County,_Iowa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Trinity_Lutheran_Church_(Friedheim,_Missouri) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Mont-Valin,_Quebec <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Market_Square_(Miamisburg,_Ohio) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Steppe <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Colorado_Mineral_Belt <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Felsberg_(Odenwald) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Białobrzegi,_Sokołów_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur-Lalande <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Chhang,_Nepal <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Eggenberg_(Graz) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Seibu_Shinjuku_Line <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bataan_National_Park <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Palace_of_Versailles <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Behemoth_(roller_coaster) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Calabria <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Mariner_6_and_7 <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Brookside_Museum <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Białobrzegi,_Legionowo_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Beckett_Nunatak <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-les-Tilleuls <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Church_of_Our_Lady_(Bremen) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bazar,_Azerbaijan <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Brackett,_Wisconsin <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Swastika <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Canna,_Calabria <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Château_La_Tour_Carnet <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Julis <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Crossroads_Mall_(Omaha) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Vinland <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Piotrowice,_Oświęcim_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Cyprien-sur-Dourdou <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre,_Orne <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Alto,_California <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Wedge_(mechanical_device) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cartouche_(design) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Labrador <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Enoggera_Dam <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Sankt_Martin_am_Wöllmißberg <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Spital_am_Pyhrn <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Ultra <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Central_Stadium_(Yekaterinburg) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre,_Oise <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Hautes-Alpes <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_588_Achilles <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boulogne_Sur_Mer <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Akbarabad,_Tonekabon <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Italian_East_Africa <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Indian_Territory <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Mud_Rural_District <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Cebeci_İnönü_Stadium <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Olmedo,_Valladolid <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biskupice-Pulkov <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Gaber,_Sofia_Province <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bartow,_West_Virginia <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dragomirești,_Vaslui <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dahlem,_Lower_Saxony <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Saint-Sauveur,_Meurthe-et-Moselle <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dali,_Cyprus <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Beauregard-de-Terrasson <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Chena_Hot_Springs,_Alaska <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Fors,_Deux-Sèvres <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dompierre-les-Tilleuls <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Everett_Wallace_House <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Bonneuil,_Charente <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Open_system_(computing) <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Zhou_dynasty <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Oregon_Trail <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Beauregard-de-Terrasson <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Boissy-en-Drouais <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Biskupice,_Miechów_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Janów,_Konin_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Dali_County <dbo_abstract> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alcanede <dbo_access> var_a brack_close
select var_a where brack_open dbr_Santa_Apolónia_railway_station <dbo_access> var_a brack_close
select var_a where brack_open dbr_Great_Dolmen_of_Comenda_da_Igreja <dbo_access> var_a brack_close
select var_a where brack_open dbr_Creake_Abbey <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Almourol <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Nossa_Senhora_da_Luz_(Lagoa) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Albany_Pine_Bush <dbo_access> var_a brack_close
select var_a where brack_open dbr_South_East_Cape <dbo_access> var_a brack_close
select var_a where brack_open dbr_Grose_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Peneda-Gerês_National_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Dolmen_of_Carapito_I <dbo_access> var_a brack_close
select var_a where brack_open dbr_Iwetemlaykin_State_Heritage_Site <dbo_access> var_a brack_close
select var_a where brack_open dbr_Považský_hrad <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Martinho_de_Cedofeita <dbo_access> var_a brack_close
select var_a where brack_open dbr_Calouste_Gulbenkian_Museum <dbo_access> var_a brack_close
select var_a where brack_open dbr_Eglin_AFB_Site_C-6 <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Santa_Cruz_(Lagoa) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Castelo_Branco <dbo_access> var_a brack_close
select var_a where brack_open dbr_Cheatham_Annex <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_of_Santo_António_(Calheta) <dbo_access> var_a brack_close
select var_a where brack_open dbr_White_Top <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Salir <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Monforte <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bickle_Knob <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Belver <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Pessegueiro <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alva <dbo_access> var_a brack_close
select var_a where brack_open dbr_Livanjsko_field <dbo_access> var_a brack_close
select var_a where brack_open dbr_Madre_de_Deus_Manor <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_George_G._Meade <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Carrazeda_de_Ansiães <dbo_access> var_a brack_close
select var_a where brack_open dbr_A_Neuve_Hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Boca_do_Vento_Elevator <dbo_access> var_a brack_close
select var_a where brack_open dbr_Residence_of_the_Crivos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_São_Francisco_(Vila_Franca_do_Campo) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Gião <dbo_access> var_a brack_close
select var_a where brack_open dbr_Egg_Rock <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Pena_de_Aguiar <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_villa_of_Vilares <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_ruins_of_Cerro_da_Vila <dbo_access> var_a brack_close
select var_a where brack_open dbr_Virginia_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_de_Fernando_Afonso <dbo_access> var_a brack_close
select var_a where brack_open dbr_W.J.B._Greenwood_Provincial_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Hemlock_Stone <dbo_access> var_a brack_close
select var_a where brack_open dbr_Archaeological_Site_of_Senhor_dos_Mártires <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_Fortress_of_Almeida <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bill_Putnam_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Leça_de_Palmeira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Avis <dbo_access> var_a brack_close
select var_a where brack_open dbr_Palacete_Silveira_e_Paulo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_São_Brás_(Vila_do_Porto) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Vila_Nova_de_Cerveira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Pousada_of_D._Maria <dbo_access> var_a brack_close
select var_a where brack_open dbr_Eternal_Light_Peace_Memorial <dbo_access> var_a brack_close
select var_a where brack_open dbr_Eternal_Light_Peace_Memorial <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Algoso <dbo_access> var_a brack_close
select var_a where brack_open dbr_Residence_Rua_de_D._Hugo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Silves <dbo_access> var_a brack_close
select var_a where brack_open dbr_Grose_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Elizabeth_Parker_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bonneville_Salt_Flats <dbo_access> var_a brack_close
select var_a where brack_open dbr_Wylie_Island <dbo_access> var_a brack_close
select var_a where brack_open dbr_Residence_of_Mesquitela <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Santa_Maria_de_Abade_de_Neiva <dbo_access> var_a brack_close
select var_a where brack_open dbr_San_Esteban,_Valencia <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_Pelada <dbo_access> var_a brack_close
select var_a where brack_open dbr_Astronomical_Observatory_of_Lisbon <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fountain_of_São_João_(Melgaço) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Guincho <dbo_access> var_a brack_close
select var_a where brack_open dbr_The_Angle <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_ruins_of_Villa_Cardillio <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Santa_Cruz_(Horta) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_São_Pedro_de_Alcântara_(São_Roque_do_Pico) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Tower_of_Ferreira_de_Aves <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Marvão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Arthur_O._Wheeler_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Degebe <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castro_of_Vila_Nova_de_São_Pedro <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Elvas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Aljustrel_mine <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_São_Pedro_do_Estoril <dbo_access> var_a brack_close
select var_a where brack_open dbr_Recreational_Forest_Reserve_of_Pinhal_da_Paz <dbo_access> var_a brack_close
select var_a where brack_open dbr_Havergate_Island <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alfândega_da_Fé <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Loulé <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_Nossa_Senhora_da_Conceição_(Angra_do_Heroísmo) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nature_Park_of_Terceira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Lamego <dbo_access> var_a brack_close
select var_a where brack_open dbr_Hermitage_of_Restelo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Nossa_Senhora_da_Rocha_(Porches) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bairro_Alto <dbo_access> var_a brack_close
select var_a where brack_open dbr_Café_A_Brasileira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Palace_of_the_Dukes_of_Braganza <dbo_access> var_a brack_close
select var_a where brack_open dbr_Amoreira_Aqueduct <dbo_access> var_a brack_close
select var_a where brack_open dbr_Palace_of_Panaca <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bom_Jesus_do_Monte_Funicular <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Negrito <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_Dam_of_Belas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_Bridge_of_Chaves <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_the_Misericórdia_de_Valadares <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Balsamão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Onset_Island_(Massachusetts) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Mateus_da_Calheta <dbo_access> var_a brack_close
select var_a where brack_open dbr_Santa_Clara_Aqueduct <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Cola <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fountain_of_Águas_Ferreas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alegrete <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Calhau_Rolado <dbo_access> var_a brack_close
select var_a where brack_open dbr_Navassa_Island <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_de_Entre_Poios <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fossil_Lake_(Oregon) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Aljezur <dbo_access> var_a brack_close
select var_a where brack_open dbr_Stanley_Mitchell_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_Nossa_Senhora_do_Carmo_(Lagoa) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Burg_Považská_Bystrica <dbo_access> var_a brack_close
select var_a where brack_open dbr_Calvin_Price_State_Forest <dbo_access> var_a brack_close
select var_a where brack_open dbr_Windmills_of_Corvo <dbo_access> var_a brack_close
select var_a where brack_open dbr_72nd_Pennsylvania_Infantry_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Malheur_Reservoir <dbo_access> var_a brack_close
select var_a where brack_open dbr_Tule_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Ruby_Beach <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Lourenço_(Almancil) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Ivanhoe_Lake_Provincial_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Guimarães_Castle <dbo_access> var_a brack_close
select var_a where brack_open dbr_Factory_House <dbo_access> var_a brack_close
select var_a where brack_open dbr_Palace_of_Ajuda <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_Temple_of_Évora <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Pedro_de_Rubiães <dbo_access> var_a brack_close
select var_a where brack_open dbr_Dyer_State_Wayside <dbo_access> var_a brack_close
select var_a where brack_open dbr_Episcopal_Palace,_Braga <dbo_access> var_a brack_close
select var_a where brack_open dbr_Megalithic_Monuments_of_Alcalar <dbo_access> var_a brack_close
select var_a where brack_open dbr_Ascensor_da_Bica <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_Povazske_Podhradie <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Mirandela <dbo_access> var_a brack_close
select var_a where brack_open dbr_Lisbon_Synagogue <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_de_Lopo_Vaz <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Mau_Vizinho_(Vila_Real) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Mount_Porte_Crayon <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fountain_of_Armés <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_São_Ramão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Vendelsöarna <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Vila_Viçosa <dbo_access> var_a brack_close
select var_a where brack_open dbr_Tower_of_Penegate <dbo_access> var_a brack_close
select var_a where brack_open dbr_Archaeological_site_of_Quinta_dos_Patudos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Burton_Wold_Wind_Farm <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_Thermae_of_Maximinus <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fountain_of_Calvo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Casa_dos_Bicos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_ruins_of_São_Cucufate <dbo_access> var_a brack_close
select var_a where brack_open dbr_Monastery_of_the_Mónicas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Palace_of_the_Counts_of_Azambuja <dbo_access> var_a brack_close
select var_a where brack_open dbr_Citânia_de_Briteiros <dbo_access> var_a brack_close
select var_a where brack_open dbr_Wadi_Rum <dbo_access> var_a brack_close
select var_a where brack_open dbr_São_Jorge_Castle <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Messejana <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Pedro_(Belazaima_do_Chão) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_dos_Vimes <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bouchout_Castle <dbo_access> var_a brack_close
select var_a where brack_open dbr_Recreational_Forest_Reserve_of_Valverde <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Redondos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Chapel_of_São_Pedro_de_Balsemão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_the_Capuchos_(Sintra) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_Carmo_(Horta) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Campo_Maior <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Santa_Bárbara_(Horta) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Castro_Laboreiro <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alfeizerão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_São_João_Baptista_(Berlengas) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Atalaia <dbo_access> var_a brack_close
select var_a where brack_open dbr_Santa_Justa_Lift <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Valongo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Sind_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Nossa_Senhora_do_Rosário_(Calheta) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_of_Sezim <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Atouguia_da_Baleia <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Paderne <dbo_access> var_a brack_close
select var_a where brack_open dbr_Soldiers'_National_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Terena <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Freixo_de_Espada-à-Cinta <dbo_access> var_a brack_close
select var_a where brack_open dbr_North_Carolina_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_villa_of_Quinta_da_Bolacha <dbo_access> var_a brack_close
select var_a where brack_open dbr_Wells_Harbour <dbo_access> var_a brack_close
select var_a where brack_open dbr_Almeida_Garrett_Library <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_da_Ermida <dbo_access> var_a brack_close
select var_a where brack_open dbr_Chapel_of_Nossa_Senhora_da_Lapa_(Sernancelhe) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Recreational_Forest_Reserve_of_Fontinhas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Braga <dbo_access> var_a brack_close
select var_a where brack_open dbr_Pousada_da_Ria <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_of_the_Tiagos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Fiães <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fountain_of_Campo_das_Hortas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nobbys_Head <dbo_access> var_a brack_close
select var_a where brack_open dbr_Betaab_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_São_Gonçalo_(Angra_do_Heroísmo) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Big_Round_Top <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Salvador_(Trofa) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Tiago_(Estômbar) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Kalvaria_Povazska_Bystrica <dbo_access> var_a brack_close
select var_a where brack_open dbr_Soldiers'_National_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Nossa_Senhora_de_Guadalupe <dbo_access> var_a brack_close
select var_a where brack_open dbr_Padrão_dos_Descobrimentos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Blidinje <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_villa_of_Santo_André_de_Almoçageme <dbo_access> var_a brack_close
select var_a where brack_open dbr_Funicular_dos_Guindais <dbo_access> var_a brack_close
select var_a where brack_open dbr_Petrovo_field,_Croatia <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Nossa_Senhora_da_Conceição_Velha <dbo_access> var_a brack_close
select var_a where brack_open dbr_Gaudineer_Knob <dbo_access> var_a brack_close
select var_a where brack_open dbr_Roman_Milestones_of_Braga <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Moreira_de_Rei <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_of_the_Noronhas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Manor_of_Lagares_d'El-Rei <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Redondo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Ducal_Palace_of_Vila_Viçosa <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alcantarilha <dbo_access> var_a brack_close
select var_a where brack_open dbr_Hudson_Highlands_State_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_the_Santíssima_Trindade_(Fátima) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_São_Miguel_do_Castelo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Coliseu_dos_Recreios <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_São_Francisco_do_Queijo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Almada <dbo_access> var_a brack_close
select var_a where brack_open dbr_De_Immigrant <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_da_Maria_Pereira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Dorsey_Knob <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fortress_of_São_Mateus_da_Calheta <dbo_access> var_a brack_close
select var_a where brack_open dbr_Hermitage_of_São_Tiago <dbo_access> var_a brack_close
select var_a where brack_open dbr_Jerónimos_Monastery <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Santa_Catarina_(Portimão) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nature_Park_of_Flores <dbo_access> var_a brack_close
select var_a where brack_open dbr_Sanctuary_of_Fátima <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Geraldo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Theatre_Circo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castro_de_Sacóias <dbo_access> var_a brack_close
select var_a where brack_open dbr_Waste_Isolation_Pilot_Plant <dbo_access> var_a brack_close
select var_a where brack_open dbr_Municipal_Palace/Hall_of_Ribeira_Grande <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alvor <dbo_access> var_a brack_close
select var_a where brack_open dbr_Beau-Séjour_Palace <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alter_Pedroso <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Valado <dbo_access> var_a brack_close
select var_a where brack_open dbr_Hospital_Pulido_Valente <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Ouvidor <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_São_João_Baptista_of_Praia_Formosa <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nature_Park_of_Santa_Maria <dbo_access> var_a brack_close
select var_a where brack_open dbr_Episcopal_Palace,_Angra_do_Heroísmo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Avô <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Santo_Estêvão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Coimbras_Chapel <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Cerrado_das_Silvas <dbo_access> var_a brack_close
select var_a where brack_open dbr_Residence_of_Portela <dbo_access> var_a brack_close
select var_a where brack_open dbr_Mikulčice_Archaeopark <dbo_access> var_a brack_close
select var_a where brack_open dbr_Virginia_Monument <dbo_access> var_a brack_close
select var_a where brack_open dbr_Bettencourt_Palace <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nazaré_Funicular <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alenquer <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Castro_Marim <dbo_access> var_a brack_close
select var_a where brack_open dbr_Pillory_of_Arcos_de_Valdevez <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Vidigueira <dbo_access> var_a brack_close
select var_a where brack_open dbr_Convent_of_São_José,_Lagoa_(Algarve) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Cranberry_Glades <dbo_access> var_a brack_close
select var_a where brack_open dbr_Blatnica_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Black_Rock_Forest <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Boi <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Ródão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Evoramonte <dbo_access> var_a brack_close
select var_a where brack_open dbr_Lolab_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Centeio <dbo_access> var_a brack_close
select var_a where brack_open dbr_Casa_Vicent <dbo_access> var_a brack_close
select var_a where brack_open dbr_Monastery_of_Dumio <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nature_Park_of_Alvão <dbo_access> var_a brack_close
select var_a where brack_open dbr_Kickapoo_Cavern_State_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Barton_Knob <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_Porto_Covo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Beja <dbo_access> var_a brack_close
select var_a where brack_open dbr_Grose_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Moinho_de_Maré_de_Corroios <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Faria <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_dos_Cubres <dbo_access> var_a brack_close
select var_a where brack_open dbr_Domus_Municipalis <dbo_access> var_a brack_close
select var_a where brack_open dbr_Ekenäs_Archipelago_National_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_do_Belo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_the_Moors <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fajã_d'Alem <dbo_access> var_a brack_close
select var_a where brack_open dbr_Redgrave_and_Lopham_Fen <dbo_access> var_a brack_close
select var_a where brack_open dbr_Gader_Valley <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fay_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Cinema_Batalha_(Porto) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Walls_of_D._Fernando/Fernandina_Wall <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Alcoutim_(Old) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Belém_Palace <dbo_access> var_a brack_close
select var_a where brack_open dbr_Menhirs_of_Lavajo <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castro_of_Cidadelhe <dbo_access> var_a brack_close
select var_a where brack_open dbr_Kidepo_Valley_National_Park <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Rebordãos <dbo_access> var_a brack_close
select var_a where brack_open dbr_Fort_of_Nossa_Senhora_da_Encarnação_(Carvoeiro) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Abbot_Pass_hut <dbo_access> var_a brack_close
select var_a where brack_open dbr_Church_of_the_Jesuit_College_(Ponta_Delgada) <dbo_access> var_a brack_close
select var_a where brack_open dbr_Nature_Park_of_Faial <dbo_access> var_a brack_close
select var_a where brack_open dbr_Gettysburg_Museum_and_Visitor_Center <dbo_access> var_a brack_close
select var_a where brack_open dbr_Aliso_Canyon <dbo_access> var_a brack_close
select var_a where brack_open dbr_Felbrigg_Hall <dbo_access> var_a brack_close
select var_a where brack_open dbr_Castle_of_Viana_do_Alentejo <dbo_access> var_a brack_close
